bportal/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals

from cms.sitemaps import CMSSitemap
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.static import serve
from core.utils import download_file

from core import views as core_views

admin.autodiscover()

urlpatterns = [
    url(r'^sitemap\.xml$', sitemap,
        {'sitemaps': {'cmspages': CMSSitemap}}),
]

urlpatterns += i18n_patterns(
    url(r'^admin/', admin.site.urls),  # NOQA
    url(r'^accounts/', include('django.contrib.auth.urls')), # accounts
    url(r'^signup/$', core_views.signup, name='signup'), #signup custom
    url(r'^account_activation_sent/$', core_views.account_activation_sent, name='account_activation_sent'), # account activation send route
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        core_views.activate, name='activate'), # activate account route
    url(r'^employer/', include('employer.urls')),
    url(r'^employee/', include('healthquestionaire.employee_urls')),
    url(r'^crud/', include('crudbuilder.urls')),
    url(r'^sss-file/', download_file),
    url(r'^login_success/', core_views.login_success, name='login_success'),
    url(r'^', include('cms.urls')),
)

# This is only needed when using runserver.
if settings.DEBUG:
    urlpatterns = [
        url(r'^media/(?P<path>.*)$', serve,
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
        ] + staticfiles_urlpatterns() + urlpatterns

healthquestionaire/urls.py
from django.conf.urls import url
from . import views
from form_application.views import ApplicationModelListView
from django.contrib.auth.decorators import login_required
from core.views import create_dependents_model_form, signatureview


urlpatterns = [
            url(r'^$', login_required(ApplicationModelListView.as_view())),
            # url(r'^questions/', login_required(HealthQuestionView.as_view(HealthQuestionView.FORMS))),
            # url(r'^employer/$', login_required(include('employer.urls'))),
            # url('^employer/edit/<int:pk>/', edit, name='employer_edit'),
            # url('^employer/create/', employerview, name='employer_create'),
            url(r'^coverage/', login_required(views.coverageview)),
            url(r'^dependents/', login_required(create_dependents_model_form)),
            url(r'^medicals/', login_required(views.create_medical_model_form)),
            url(r'^medications/', login_required(views.create_medication_model_form)),
            url(r'^dependentinfo/', login_required(views.dependentinfoview)),
            url(r'^signpdf/', login_required(signatureview)),
        ]

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import EmployeeDependent, HeightWeight, LookupModel
from django.contrib.admin import widgets 
from django.forms import modelformset_factory
from employer.models import Employer
class SignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.', required=True)
    birth_date = forms.DateField(help_text='Required. Format: YYYY-MM-DD', required=True)
    employer = forms.ModelChoiceField(queryset=Employer.objects.all(), required=True)

    class Meta:
        model = User
        fields = ('username', 'email', 'birth_date', 'employer', 'password1', 'password2', )

class HeightWeightForm(forms.ModelForm):
    class Meta:
        model = HeightWeight
        exclude=()

DependentsFormset = modelformset_factory(
    EmployeeDependent,
    fields='__all__',
    extra=1
)

class EmployeeDependentForm(forms.ModelForm):
    class Meta:
        model = EmployeeDependent
        exclude=('employee','age',)
        widgets = {
             'ssn': forms.TextInput(attrs={'class': 'masked', 'pattern': '^([1-9])(?!\1{2}-\1{2}-\1{4})[1-9]{2}-[1-9]{2}-[1-9]{4}$', 'placeholder': '999-99-9999'}),
             'dob_dependent': forms.DateInput(format='%d/%m/%Y', attrs={'class': 'masked', 'pattern': '^(((0?[1-9]|1[012])/(0?[1-9]|1\d|2[0-8])|(0?[13456789]|1[012])/(29|30)|(0?[13578]|1[02])/31)/(19|[2-9]\d)\d{2}|0?2/29/((19|[2-9]\d)(0[48]|[2468][048]|[13579][26])|(([2468][048]|[3579][26])00)))$', 'placeholder': 'MM/dd/yyyy'})
        }
        # 'tobacco_use': forms.CheckboxInput(attrs={ 'style': 'width:50px; height: 50px;' }),
    
    def __init__(self, *args, **kwargs):
        super(EmployeeDependentForm, self).__init__(*args, **kwargs)
        self.fields['tobacco_use'].queryset = LookupModel.objects.filter(type_lookup='yes_no')
        self.fields['relationship'].queryset = LookupModel.objects.filter(type_lookup='employee_relationship')
        self.fields['gender'].queryset = LookupModel.objects.filter(type_lookup='gender')
        self.header = 'Dependents'

class SignatureForm(forms.Form):
    sign_data = forms.CharField(max_length=1024)

healthquestionaire/views.py
import io
from django.http import FileResponse
from reportlab.pdfgen import canvas
from formtools.wizard.views import SessionWizardView
from django.shortcuts import render, redirect, get_object_or_404
from .forms import EmployerAddressForm, EmployeeAddressForm, CoverageForm, EmployeeModelForm
from core.utils import write_fillable_pdf
from .process_submitted_data import process_data
from .forms import MedicalModelFormset, MedicationModelFormset, DependentInfoForm
from .models import MedicalModel, MedicationModel, EmployeeModel, CoverageModel, DependentInfoModel
from django.views.generic.edit import CreateView, UpdateView
from django.http import Http404
from form_application.models import ApplicationModel
from django.core.exceptions import ValidationError
from django.conf import settings
from django.db import connection
from employer.models import Employer
import pdfrw
import enum


def get_employee_instance(user, employee_id):
    try:
        print(enum.__file__, 'enum')
        if employee_id:
            employee = get_object_or_404(EmployeeModel, id=employee_id)
        elif user:
            employee = get_object_or_404(EmployeeModel, login_user=user)
        else:
            return None
        
        print('employee check', employee_id, employee.id)
        return employee
    except Http404:
        return None
        
def create_medical_model_form(request):
    template_name = 'medical_formset.html'
    heading_message = 'Health Information Details'
    heading_direction = 'If you answer “Yes” to any of the previous Health History questions, please provide detail in form provided below.'
    employee = get_employee_instance(request.user, request.GET.get('employee', None))
    
    if request.method == 'GET':
        # we don't want to display the already saved model instances
        formset = MedicalModelFormset(queryset=MedicalModel.objects.none())
    elif request.method == 'POST':
        formset = MedicalModelFormset(request.POST)
        if formset.is_valid():
            for form in formset:
                # only save if name is present
                if employee:
                    saved_data = form.save(commit=False)
                    saved_data.employee = employee
                    saved_data.save()
            return redirect(''.join([settings.PREFIX_URL, 'medicals/?toolbar_off&employee=', str(employee.id)]))
    return render(request, template_name, {
            'formset': formset,
            'back_url': ''.join([settings.PREFIX_URL,'dependentinfo/?toolbar_off&employee=', str(request.GET.get('employee', ''))]),
            'medical_list': MedicalModel.objects.filter(employee=employee),
            'heading': heading_message,
            'heading_direction': heading_direction,
            'PREFIX_URL': settings.PREFIX_URL,
        })

def create_medication_model_form(request):
    template_name = 'medication_formset.html'
    heading_message = 'Medication List'
    heading_direction = 'Please list any medications, prescriptions, or injections taken in the last 12 months'
    employee = get_employee_instance(request.user, request.GET.get('employee', None))
    
    if request.method == 'GET':
        # we don't want to display the already saved model instances
        formset = MedicationModelFormset(queryset=MedicationModel.objects.none())
    elif request.method == 'POST':
        formset = MedicationModelFormset(request.POST)
        if formset.is_valid():
            for form in formset:
                # only save if name is present
               if employee:
                    saved_data = form.save(commit=False)
                    saved_data.employee = employee
                    saved_data.save()
            return redirect(''.join([settings.PREFIX_URL, 'medications/?toolbar_off&employee=', str(employee.id)]))
    return render(request, template_name, {
            'formset': formset,
            'back_url': ''.join([settings.PREFIX_URL,'dependents/?toolbar_off&employee=', str(request.GET.get('employee', ''))]),
            'medical_list': MedicationModel.objects.filter(employee=employee),
            'heading': heading_message,
            'heading_direction': heading_direction,
            'PREFIX_URL': settings.PREFIX_URL,
        })

def some_view(request):
    # Create a file-like buffer to receive PDF data.
    buffer = io.BytesIO()

    # Create the PDF object, using the buffer as its "file."
    p = canvas.Canvas(buffer)

    # Draw things on the PDF. Here's where the PDF generation happens.
    # See the ReportLab documentation for the full list of functionality.
    p.drawString(100, 100, "Hello world.")

    # Close the PDF object cleanly, and we're done.
    p.showPage()
    p.save()

    # FileResponse sets the Content-Disposition header so that browsers
    # present the option to save the file.
    return FileResponse(buffer, as_attachment=True, filename='media/pdf-templates/LHP_Employee_Health_Application_2019.pdf')

# class HealthQuestionView(SessionWizardView):
#     FORMS = [
#         ("employer", EmployerAddressForm),
#         ("employee", EmployeeAddressForm)
#         #  ("coverage", CoverageForm),
#         #  ("dependents", EmployeeDependentForm )
#         ]

#     # TEMPLATES = {"employee": "questions/employee_form.html",
#     #          "coverage": "questions/employee_coverage_form.html",
#     #          "dependents": "questions/employee_dependent_form.html"}
#     template_name = 'health_wizard.html'
#     # def get_template_names(self):
#     #     return [self.TEMPLATES[self.steps.current]]
    
#     def done(self, form_list, **kwargs):
#         submitted_data = [form.cleaned_data for form in form_list]
#         try:
#             employee = process_data(self.request, submitted_data)
#         except Exception as ex:
#             print(ex, 'error generic')
        
#         response = redirect(''.join([settings.PREFIX_URL,'coverage/?toolbar_off&empl_id=', str(employee.id)]))
#         return response


class CoverageModelCreateView(CreateView):
    form_class = CoverageForm
    template_name = "healthquestionaire/coverage_form.html"
    success_url = '/medicals/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["back_url"] = ''.join(['employee/edit/', str(self.request.GET.get('employee', '')), '/?toolbar_off'])
        return context

def employeeview(request):
    employer_id = request.GET.get('employer', None)
    heading_message = 'Employee Information'
    heading_direction = 'Please complete all details below.'
    user = request.user
    if request.method == 'POST':
        try:
            # print(request.GET.get('id', None))
            employee = get_object_or_404(EmployeeModel, login_user_id=request.user)
            form = EmployeeModelForm(request.POST, instance=employee)
        except Http404:
            form = EmployeeModelForm(request.POST)
        if form.is_valid():
            saved_data = form.save(commit=False)
            saved_data.login_user = user
            saved_data.all_forms_completed = False
            saved_data.save()
            print(user, 'login user', saved_data.login_user)
            try:
                employer = get_object_or_404(Employer, id=employer_id)
                employer.employee.add(EmployeeModel.objects.get(id=saved_data.id))
            except Http404:
                print('Cannot find employer')            
            return redirect(''.join([settings.PREFIX_URL,'coverage/?toolbar_off&employee=', str(saved_data.id)]))
    print(request.GET.get('id', None))
    if request.GET.get('id', None):
        employee = get_object_or_404(EmployeeModel, id=request.GET.get('id', None))
        print(employee)
        form = EmployeeModelForm(instance=employee)
    else:
        try:
            employee = get_object_or_404(EmployeeModel, login_user=user)
            form = EmployeeModelForm(instance=employee)
        except Http404:
            form = EmployeeModelForm(initial={ 'login_user': request.user, 'all_forms_completed': False, 
                'fk_employer': user.profile.employer, 'empl_dob': user.profile.birth_date, 
                'email_address': user.email})
    return render(request,'healthquestionaire/employee_form.html',{'form': form, 'heading': heading_message, 'heading_direction': heading_direction, 'back_url': settings.PREFIX_URL})

def coverageview(request):
    employee = get_employee_instance(request.user, request.GET.get('employee', None))
    heading_message = 'Insurance Coverage'
    heading_direction = 'Please complete aplicable fields below.'
    if request.method == 'POST':
        print('POST FORM coverage', request.POST)
        try:
            coverage = get_object_or_404(CoverageModel, employee=employee)
            form = CoverageForm(request.POST, instance=coverage)
        except Http404:
            form = CoverageForm(request.POST)
        if form.is_valid():
            if employee:
                saved_data = form.save(commit=False)
                saved_data.employee = employee
                saved_data.save()
            # print(saved_data)
            return redirect(''.join([settings.PREFIX_URL, 'dependents/?toolbar_off&employee=', str(employee.id)]))
        else:
            print(form.errors)

    print(request.GET.get('employee', None))
    if request.GET.get('employee', None):
        print('testing')
        try:
            coverage = get_object_or_404(CoverageModel, employee=employee)
            form = CoverageForm(instance=coverage)
        except Http404:
            form = CoverageForm(initial={'employee': employee})
    else:
        return redirect(''.join([settings.PREFIX_URL, 'employee/create/?toolbar_off']))

templates/healthquestionaire/coverage_form.html
{% extends 'base_create_form.html' %}

templates/healthquestionaire/dependentinfo_form.html
{% extends "fullwidth.html" %}
{% load cms_tags %}
{% load i18n %}

{% block content %}
<div class="container">
        {% if heading %}
        <h4>{{ heading }}</h4>
        <p>{{ heading_direction }}</p>
        {% endif %}
        
    <form class="form-horizontal" method="POST" action="">
        {% csrf_token %}
        <div class="row">
            {% if form.errors %}
                {% for field in form %}
                    {% for error in field.errors %}
                        <div class=" col s12 alert alert-danger">
                            <strong>{{ error|escape }}</strong>
                        </div>
                    {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                    <div class="col s12 alert alert-danger">
                        <strong>{{ error|escape }}</strong>
                    </div>
                {% endfor %}
            {% endif %}
        </div>
        <div class="row">
            {% for field in form %}
            <!-- {{field.html_name}} -->
                {% if field.html_name == 'diagnose_treated' %}
                <div class="input-field col s12">
                    <span>
                        {{ field.label_tag }}
                        {% if field.help_text %}
                        <sup>{{ field.help_text }}</sup>
                        {% endif %}
                        {{ field }} 
                    </span>
                </div>
                {% elif field.field.widget.input_type == 'checkbox' %}
                <div class="input-field col s4">
                    <span>
                        <div class="col s12">
                            {{ field.label_tag }}
                        </div>
                        {% for check in field %}
                            <div class="col s12">
                                <label>
                                    <input name="{{ field.html_name }}" type="checkbox" />
                                    <span>{{ check.choice_label }}</span>
                                </label>
                                {{ check }}
                            </div>
                        {% endfor %}
                    </span>
                </div>
                {% elif field.field.widget.input_type == 'radio' %}
                <div class="input-field col s4">
                    <span>
                        <div class="col s12">
                            {{ field.label_tag }}
                        </div>
                        {% for radio in field %}
                            {% if radio.choice_label != '---------' %}
                            <div class="col s3">
                                <label>
                                    <input name="{{field.html_name}}" type="radio" />
                                    <span>{{ radio.choice_label }}</span>
                                </label>
                            </div>
                            {% endif %}
                        {% endfor %}
                    </span>
                </div>
                {% else %}
                <div class="input-field col s6">
                <span>
                    {{ field.label_tag }}
                    {% if field.help_text %}
                    <sup>{{ field.help_text }}</sup>
                    {% endif %}
                    {{ field }} 
                </span>
                </div>
                {% endif %}
            {% endfor %}
        </div>
        <div class="row">
                <div class="col s11">

            {% if back_url %}
                    <a href="{{ back_url }}" class="btn">Back</a>
               
            {% endif %}
        </div>
            <div class="col s1">
                <!--    <a href="{{ next_url }}" class="btn">Next</a>-->
                 <button type="submit" class="btn btn-block btn-primary">Next</button> 
            </div>
        </div>
    </form>
</div>
<script>
    document.addEventListener('DOMContentLoaded', function() {
        var select_elems = document.querySelectorAll('select');
        var select_instances = M.FormSelect.init(select_elems, {});
        var elems = document.querySelectorAll('.datepicker');
        var instances = M.Datepicker.init(elems, {'format': 'mm/dd/yyyy', 'changeMonth': true,
        'changeYear': true,
        'yearRange': '1900:2012'});

        var masking = {

            // User defined Values
            //maskedInputs : document.getElementsByClassName('masked'), // add with IE 8's death
            maskedInputs : document.querySelectorAll('.masked'), // kill with IE 8's death
            maskedNumber : 'XdDmMyY9',
            maskedLetter : '_',
          
            init: function () {
              masking.setUpMasks(masking.maskedInputs);
              masking.maskedInputs = document.querySelectorAll('.masked'); // Repopulating. Needed b/c static node list was created above.
              masking.activateMasking(masking.maskedInputs);
            },
          
            setUpMasks: function (inputs) {
              var i, l = inputs.length;
          
              for(i = 0; i < l; i++) {
                masking.createShell(inputs[i]);
              }
            },
            
            // replaces each masked input with a shall containing the input and it's mask.
            createShell : function (input) {
              var text = '', 
                  placeholder = input.getAttribute('placeholder');
              if (placeholder){
                input.setAttribute('maxlength', placeholder.length);
                input.setAttribute('data-placeholder', placeholder);
                input.removeAttribute('placeholder');
                
                if (input.value.length === placeholder.length){
                  text = '<span class="shell">' +
                    '<span aria-hidden="true" id="' + input.id + 
                    'Mask"><i></i></span>' + 
                    input.outerHTML +
                    '</span>';
                } else {
                  text = '<span class="shell">' +
                    '<span aria-hidden="true" id="' + input.id + 
                    'Mask"><i></i>' + placeholder + '</span>' + 
                    input.outerHTML +
                    '</span>';
                }
                
                input.outerHTML = text;
              }
            },
          
            setValueOfMask : function (e) {
              var value = e.target.value,
                  placeholder = e.target.getAttribute('data-placeholder');
              
              return "<i>" + value + "</i>" + placeholder.substr(value.length);
            },
            
            // add event listeners
            activateMasking : function (inputs) {
              var i, l;
          
              for (i = 0, l = inputs.length; i < l; i++) {
                if (masking.maskedInputs[i].addEventListener) { // remove "if" after death of IE 8
                  masking.maskedInputs[i].addEventListener('keyup', function(e) {
                    masking.handleValueChange(e);
                  }, false); 
                } else if (masking.maskedInputs[i].attachEvent) { // For IE 8
                    masking.maskedInputs[i].attachEvent("onkeyup", function(e) {
                    e.target = e.srcElement; 
                    masking.handleValueChange(e);
                  });
                }
              }
            },
            
            handleValueChange : function (e) {
              var id = e.target.getAttribute('id');
                  
              switch (e.keyCode) { // allows navigating thru input
                case 20: // caplocks
                case 17: // control
                case 18: // option
                case 16: // shift
                case 37: // arrow keys
                case 38:
                case 39:
                case 40:
                case  9: // tab (let blur handle tab)
                  return;
                }
          
              document.getElementById(id).value = masking.handleCurrentValue(e);
              document.getElementById(id + 'Mask').innerHTML = masking.setValueOfMask(e);
          
            },
          
            handleCurrentValue : function (e) {
              var isCharsetPresent = e.target.getAttribute('data-charset'), 
                  placeholder = isCharsetPresent || e.target.getAttribute('data-placeholder'),
                  value = e.target.value, l = placeholder.length, newValue = '', 
                  i, j, isInt, isLetter, strippedValue;
          
              // strip special characters
              strippedValue = isCharsetPresent ? value.replace(/\W/g, "") : value.replace(/\D/g, "");
          
              for (i = 0, j = 0; i < l; i++) {
                  var x = 
                  isInt = !isNaN(parseInt(strippedValue[j]));
                  isLetter = strippedValue[j] ? strippedValue[j].match(/[A-Z]/i) : false;
                  matchesNumber = masking.maskedNumber.indexOf(placeholder[i]) >= 0;
                  matchesLetter = masking.maskedLetter.indexOf(placeholder[i]) >= 0;
          
                  if ((matchesNumber && isInt) || (isCharsetPresent && matchesLetter && isLetter)) {
          
                          newValue += strippedValue[j++];
          
                    } else if ((!isCharsetPresent && !isInt && matchesNumber) || (isCharsetPresent && ((matchesLetter && !isLetter) || (matchesNumber && !isInt)))) {
                          // masking.errorOnKeyEntry(); // write your own error handling function
                          return newValue; 
          
                  } else {
                      newValue += placeholder[i];
                  } 
                  // break if no characters left and the pattern is non-special character
                  if (strippedValue[j] == undefined) { 
                    break;
                  }
              }
              if (e.target.getAttribute('data-valid-example')) {
                return masking.validateProgress(e, newValue);
              }
              return newValue;
            },
          
            validateProgress : function (e, value) {
              var validExample = e.target.getAttribute('data-valid-example'),
                  pattern = new RegExp(e.target.getAttribute('pattern')),
                  placeholder = e.target.getAttribute('data-placeholder'),
                  l = value.length, testValue = '';
          
              //convert to months
              if (l == 1 && placeholder.toUpperCase().substr(0,2) == 'MM') {
                if(value > 1 && value < 10) {
                  value = '0' + value;
                }
                return value;
              }
              // test the value, removing the last character, until what you have is a submatch
              for ( i = l; i >= 0; i--) {
                testValue = value + validExample.substr(value.length);
                if (pattern.test(testValue)) {
                  return value;
                } else {
                  value = value.substr(0, value.length-1);
                }
              }
            
              return value;
            },
          
            errorOnKeyEntry : function () {
              // Write your own error handling
            }
          }
          
          masking.init();
    });
</script>
<style>



.shell {
  position: relative;
  line-height: 1; }
  .shell span {
    position: absolute;
    left: 3px;
    top: 1px;
    color: #ccc;
    pointer-events: none;
    z-index: -1; }
    .shell span i {
      font-style: normal;
      /* any of these 3 will work */
      color: transparent;
      opacity: 0;
      visibility: hidden; }

input.masked,
.shell span {
  font-size: 16px;
  font-family: monospace;
  padding-right: 10px;
  background-color: transparent;
  text-transform: uppercase; }

</style>

{% endblock %}

templates/healthquestionaire/done.html
{% extends "fullwidth.html" %}
{% load cms_tags %}
{% load i18n %}

{% block content %}

<div class="container">
<script src="https://cdn.jsdelivr.net/npm/signature_pad@2.3.2/dist/signature_pad.min.js"></script>
<h4>AGREEMENTS, AUTHORIZATION & ATTESTATION</h4>
<p>Please review your completed application below.  Once all provided information is complete and accurate, please read section 7 at the end of the PDF and sign using the signature card below.
    </p>
<div class="row">
    <div class="col s12">
        {% if signed_pdf_file != '' %}
            <input type="hidden" id="hidden-pdf-file-url" value="{{ signed_pdf_file }}">
            <a href="{{ signed_pdf_file }}" target="_blank">Open Completed PDF Application</a>
            <div>
                <object data="{{ signed_pdf_file }}" type="application/pdf" width="100%" height="700px">
                alt : <a href="{{ signed_pdf_file }}">Open Completed PDF Application</a>
                </object>
            </div>
            
        {% else %}
            <div><h3>NO SIGNED PDF FILE</h3></div>
        {% endif %}
    </div>
    <div class="col s12">
        {% if not check_signed_file %}
        <form id="signForm" method="POST" action="">
            {% csrf_token %}
            <div class="card grey darken-1" style="padding-bottom:0px;" width="100%">
                <!-- {{ form.as_p }} -->
                {% if error_status %}
                <div class="card-panel red lighten-2">{{ error_status }}</div>
                {% endif %}
                <input type="hidden" name="sign_data" maxlength="1024" required id="id_sign_data" />
                <div class="card-content white-text" style="padding-bottom:0px;" width="100%">
                    <span class="card-title">Please Sign Below</span>
                    <canvas id="cvs-sign-pad" width="800"></canvas>

                </div> 
               
                <div class="card-action">
                    <button onclick="clearSignature()" class="btn"  style="background-color:#992A43;">Clear</button>
                    <button onclick="submitSignature()" class="btn"  style="background-color:#992A43;">Submit</button>
                </div>
            </div>                
        </form>
        {% endif %}
    </div>
</div>
<br><br>
<div class="row">
        {% if not check_signed_file %}
            <div class="col s11">
                <a class="waves-effect waves-light btn" href="{{PREFIX_URL}}medicals/?employee={{ request.GET.employee }}">Back</a>
            </div>
        {% endif %}
        <div class="col s1">
            <a class="waves-effect waves-light btn" href="{{PREFIX_URL}}?toolbar_off">Finish</a>
        </div>
    </div>
</div>
<script>
    var canvas = document.querySelector("#cvs-sign-pad");
    var signature = null;
    if (canvas){
        signaturePad = new SignaturePad(canvas);
    }
    
    function clearSignature(ev) {
        signaturePad.clear();
    }

    function submitSignature(ev) {
        const data = signaturePad.toDataURL();
        document.getElementsByName('sign_data')[0].value = data;
        //document.getElementById('signForm').submit();
    }
    
</script>
{% endblock %}

templates/healthquestionaire/employee_form.html
{% extends 'base_create_form.html' %}